import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import localFont from "next/font/local";
import { Work_Sans } from "next/font/google";
import "./globals.scss";
import JotaiProvider from "@/components/providers/jotai";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

const avenirNext = localFont({
  src: "./fonts/AvenirNextLTPro-Regular.otf",
  variable: "--font-avenir-next",
  weight: "100 900",
});

const avenirNextBold = localFont({
  src: "./fonts/AvenirNextLTPro-Bold.otf",
  variable: "--font-avenir-next-bold",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${avenirNext.variable} ${avenirNextBold.variable} ${workSans.variable}`}
      >
        <JotaiProvider>{children}</JotaiProvider>
      </body>
    </html>
  );
}
